version: '3.7'
services:
    wiki-db:
        image: postgres:15.3
        container_name: wiki-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: wiki
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        logging:
            driver: "none"
        volumes:
            - ./wiki_db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d wiki -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 3
    wiki:
        image: ghcr.io/requarks/wiki:2.5
        container_name: wiki
        restart: unless-stopped
        environment:
            DB_TYPE: postgres
            DB_HOST: wiki-db
            DB_PORT: 5432
            DB_USER: ${POSTGRES_USER}
            DB_PASS: ${POSTGRES_PASSWORD}
            DB_NAME: wiki
        ports:
            - "3100:3000"
        depends_on:
            wiki-db:
                condition: service_healthy
